### ISSUE TITLE
Link to get API key broken

### ISSUE THREAD

**Issue by tim-durrant** [lucasbranddao/Movie-List-App#2]
Still possible to obtain an API key?

**Comment by lucasbranddao** [comment]
Yes! Try this link: http://www.omdbapi.com/apikey.aspx

**Comment by tim-durrant** [comment]
That’s what the issue is man, it doesn’t work lol

**Comment by lucasbranddao** [comment]
Be more specific. I just fetched a new key.

**Comment by tim-durrant** [comment]
My apologies Lucas.  My DNS server was blocking the URL.
